### ISSUE TITLE
Criar estrutura inicial para lib python

### ISSUE THREAD

**Issue by gabubellon** [gabubellon/streamyard-downloader#9]
Objetivo e criar uma lib python desse projeto

**Comment by andreztz** [comment]
Posso resolver essa issue?

**Comment by gabubellon** [comment]
@andreztz Se quiser se assinar e trabalhar nela em um fork fica a vontade :D
Só depois queria ver como será feito até pra eu aprender

**Comment by andreztz** [comment]
@gabubellon pode atribuir esta issue ao meu usuário, obrigado.
